#!/usr/bin/env node

var sentry = require("sentry");
var sys = require('util');
var exec = require('child_process').exec;

console.log("Sentry is watching for changes in the project.");

//Check for changes on the source files and test them if there is any.
sentry.watch("src/*.js", function(filename){
	exec("jake", function (error, stdout, stderr) {
		sys.print(stdout);
	});
});